### ISSUE TITLE
Add info about color blindness

### ISSUE THREAD

**Issue by untill** [NorskRegnesentral/ccc21#11]

**Comment by joschuaos** [comment]
Fargeblindhet er en variasjon i fargesynet som karakteriseres ved at man ikke kan se forskjell mellom to eller flere farger eller at man ikke kan gjenkjenne farger i omgivelsen. Omtrent 1 i 10 menn har en eller annen form av nedsatt fargesyn, samtidig at det er mindre enn 1% av kvinnene som opplever fargeblindhet. Å være fargeblind betyr ikke at man ser verden i svart og hvit. De aller fleste med nedsatt fargesyn nyter farger, men omfanget av de opplevde fargene er noe redusert sammenliknet med en "normal" seende. 

Ved å trykke på knappene nedenfor, kan du velge en av de mest vanlige fargeblindhetene for å se hvordan noen med nedsatt fargesyn opplever farger sammenliknet med en normal seende.
