### ISSUE TITLE
Scrollbar icons are too small, have poor contrast, and are visible when not needed

### ISSUE THREAD

**Issue by untill** [NorskRegnesentral/ccc21#40]

**Comment by thorkr** [comment]
Contrast and visibility improved in commit 2cb95d5c59021ca2a3500a2cbc6b4a90304805c0.

**Comment by joschuaos** [comment]
Is this fixed? @thorkr

**Comment by joschuaos** [comment]
Bra. Bare close 😊

ons. 29. mar. 2023, 12:32 skrev Thor Kristoffersen ***@***.***
