### ISSUE TITLE
1. Create a global variable for the  color deficiency type

### ISSUE THREAD

**Issue by drjoschua** [NorskRegnesentral/ccc21#56]
The color deficiency type defines the type of color deficiency used globally on the webpage:
* Ingen
* Protan
* Deutan
* Tritan

(The picture says sim_method but it should say sim_type.)
![2023-03-03_cc21_glob-variables](https://user-images.githubusercontent.com/69462195/222725619-bf0401c1-c414-4707-a946-c4ee89f1622c.jpg)

**Comment by thorkr** [comment]
Implemented in commit ac6e0af9b5a15ace776a952a97dc425c4ff82531
