### ISSUE TITLE
2. Create global variable for the simulated colors

### ISSUE THREAD

**Issue by drjoschua** [NorskRegnesentral/ccc21#58]
Parallel to the original colors, we should store an array with the simulated colors. 

(The picture says sim_method but it should say sim_type.)
![2023-03-03_cc21_glob-variables](https://user-images.githubusercontent.com/69462195/222725908-9480d63f-9dd0-40fe-b5c8-2f020ebfb5dd.jpg)

**Comment by thorkr** [comment]
Implemented in commit ac6e0af9b5a15ace776a952a97dc425c4ff82531
