### ISSUE TITLE
4. Present the simulated colors next to the original colors in the color picker

### ISSUE THREAD

**Issue by drjoschua** [NorskRegnesentral/ccc21#59]
The simulated colors should be presented next to the original colors in the color picker. This can be done other by splitting the color sqaure in two or by adding a separate box next to it. The hexa value of the simulated colors could be shown grayed out. When color type ingen has been chosen the two colors are the same. In the ingen case the value of the simulated colors does not need to be shown.

(The picture says sim_method but it should say sim_type.)
![2023-03-03_cc21_gui-1](https://user-images.githubusercontent.com/69462195/222729203-5b54c65d-17ff-47d9-bdbd-fa788e749077.jpg)
![2023-03-03_cc21_colors-sim](https://user-images.githubusercontent.com/69462195/222729034-5c9da5bb-8134-4c30-b6e7-2a548d62db31.jpg)

**Comment by thorkr** [comment]
Implemented in commit ac6e0af9b5a15ace776a952a97dc425c4ff82531
