### ISSUE TITLE
2. Send original colors to the server

### ISSUE THREAD

**Issue by drjoschua** [NorskRegnesentral/ccc21#62]
The original colors saved globally from the page should be packed into a JSON object with the following structure:
```
{
   "simulation_type":  simulation_type,
   "colors_orig": colors_orig
}
```

The function should wait for a reply. If successful (HTTP code 200), it will receive a JSON object of the following structure:
```
{
   "simulation_type":  simulation_type,
   "colors_sim": colors_sim
}
```
colors_sim should then be stored in the global variable for the simulated colors.
If fail (any other HTTP code), there should be a warning that something went wrong. The functtion should then save the original colors in the global variable for the simulated colors and set the global variable for simulaiton type to ingen.

(The picture says sim_method but it should say sim_type.)
![2023-03-03_cc21_server](https://user-images.githubusercontent.com/69462195/222728702-a48f3d99-388b-495b-ac85-f1c8ee0c50d8.jpg)
![2023-03-03_cc21_server-og-daltonize](https://user-images.githubusercontent.com/69462195/222730308-ace59d19-8afe-4bbe-9e54-c5fc56545358.jpg)

**Comment by thorkr** [comment]
Color vision deficiencies simulated using Brettel algorithm in commit 6fac8bc2edf3594ee647a78bebe0df8c4cc0236f
