### ISSUE TITLE
3. Write function to simulate array with colors

### ISSUE THREAD

**Issue by drjoschua** [NorskRegnesentral/ccc21#66]
Write a function that takes simulation_type and array with original colors as input. Compute simualted colors. Return simulation_type and array with simulation colors.

![2023-03-03_cc21_simulate](https://user-images.githubusercontent.com/69462195/222731895-539d9a67-6048-4746-ae4b-27a3f230c78b.jpg)

**Comment by joschuaos** [comment]
- [ ] Write function
"""
def simulate(arr):
   return arr
"""

**Comment by joschuaos** [comment]
We used a JavaScript library instead.
