### ISSUE TITLE
4. Integrate simulate function into the server

### ISSUE THREAD

**Issue by drjoschua** [NorskRegnesentral/ccc21#67]
Integrate the previously created simulate function into the server. Retrieve JSON data from the POST/GET request. Pack the returned JSON object into a POST/GET request directed towards CC21.
![2023-03-03_cc21_server-og-simulate](https://user-images.githubusercontent.com/69462195/222731738-18e1a8ad-d4a8-4496-97d5-340518c10e47.jpg)
![2023-03-03_cc21_simulate](https://user-images.githubusercontent.com/69462195/222731746-8fa240b8-2065-4c2f-a172-8703e42b389e.jpg)

**Comment by joschuaos** [comment]
We used a JavaScript library instead.
