### ISSUE TITLE
Install PYTHON libraries on the server.

### ISSUE THREAD

**Issue by joschuaos** [NorskRegnesentral/ccc21#72]
The colordeficiency script will run on Python3 with the following dependencies:
- [ ] numpy
- [ ] matplotlib
- [ ] scipy

**Comment by untill** [comment]
Er dette med Python3 et absolutt krav? På serveren kjører Python 2.7.17.

**Comment by untill** [comment]
Dessuten: Hvor er skriptet jeg trenger?

**Comment by joschuaos** [comment]
Vi bør ha Python3, ja.

**Comment by untill** [comment]
Har upgradert til Python 3.8.10. (Ubuntu 20.04)

**Comment by joschuaos** [comment]
We used a JavaScript library instead.
