### ISSUE TITLE
Reference ColorBrewer

### ISSUE THREAD

**Issue by joschuaos** [NorskRegnesentral/ccc21#78]
Reference to the [ColorBrewer 2.0 website](https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3) under the «Kom igang» tab: 

> The valgte fargepalettene ble inspirert av ColorBrewer 2.0. Du finner flere eksempler på tilgjengelig og brukervennlige fargepaletter under:n https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3

> The chosen color palettes have been inspired by ColorBrewer 2.0. You can find more examples for accessible and usable color palettes under: https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3

**Comment by drjoschua** [comment]
Added link to ColorBrewer 2.0 & Color Hunt.
