### ISSUE TITLE
Add a "tutorial" to the front page

### ISSUE THREAD

**Issue by joschuaos** [NorskRegnesentral/ccc21#79]
Describe on the front page (maybe with links) what the user can expect from and do on the page.

> Hovedmålet med denne nettsiden er å øke tilgjengeligheten av visuell informasjon i digitale brukergrensesnitt og gjøre det enklere å oppfylle WCAG 2.1-kravene. Web Content Accessibility Guidelines 2.1 (WCAG 2.1) er en nettstandard som omhandler tilgjengelighet og brukervennlighet av digitale brukergrensesnitt. Denne standarden er blant annet pålagt i Forskrift om universell utforming av IKT-løsninger.
>
> På nettsiden kan du velge farger under «Din palett». Du kan starte med noen tilgjengelige og brukervennlige fargepaletter som du finner under «Kom i gang». Kontrastverdiene vises under «Kontraster». Under «Anbefalinger» kan du se hvor og når de valgte fargene er passende, mindre passende eller ikke egnet i det hele tatt. Du kan også simulere ulike typer fargeblindhet under «Fargeblindhet». Du finner mer informasjon om WCAG under «WCAG». 
>
> Kontrastberegningen er basert på WCAG 2.1-standarden. Nettsiden er utformet for å være universelt tilgjengelig, inkludert støtte for skjermlesere. Hvis du oppdager en feil, er du velkommen til å ta kontakt slik at vi kan rette den.

**Comment by drjoschua** [comment]
Added «Snarveier» to  «Om CCC 2.1» tab.
